### ISSUE TITLE
Services - a communication strategy

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.github.io#77]
@meekrosoft and @lakruzz are meeting in Göteborg on Dec 17th to go through and try to identify Praqma's signature services, have to communicate and present them.

This might affect the services description on the web site so currently the following tasks are to be considered sub tasks to this one:

- [x] Copy for "tool specialists" #76 
- [x] Copy for "Service level agreement" #75
- [x] Copy for "Josra" #74 
- [x] Copy for "Consulting" #73
- [x] Copy for "CoDe conferences and meetups" #72
- [x] Copy for "Assessments" #71
